### ISSUE TITLE
create-image.sh: volume group not found

### ISSUE THREAD

**Issue by Gooberpatrol66** [z3ntu/cross-hurd#3]
grub-install returns

```
File descriptor 21 (socket:[22068]) leaked on vgs invocation. Parent PID 23172: grub-install
File descriptor 22 (socket:[53185]) leaked on vgs invocation. Parent PID 23172: grub-install
File descriptor 24 (socket:[50487]) leaked on vgs invocation. Parent PID 23172: grub-install
File descriptor 25 (socket:[23417]) leaked on vgs invocation. Parent PID 23172: grub-install
File descriptor 30 (socket:[23406]) leaked on vgs invocation. Parent PID 23172: grub-install
File descriptor 70 (socket:[62725]) leaked on vgs invocation. Parent PID 23172: grub-install
File descriptor 75 (socket:[62766]) leaked on vgs invocation. Parent PID 23172: grub-install
  WARNING: Failed to connect to lvmetad. Falling back to device scanning.
  Volume group "loop2p1" not found
  Cannot process volume group loop2p1
File descriptor 21 (socket:[22068]) leaked on vgs invocation. Parent PID 23172: grub-install
File descriptor 22 (socket:[53185]) leaked on vgs invocation. Parent PID 23172: grub-install
File descriptor 24 (socket:[50487]) leaked on vgs invocation. Parent PID 23172: grub-install
File descriptor 25 (socket:[23417]) leaked on vgs invocation. Parent PID 23172: grub-install
File descriptor 30 (socket:[23406]) leaked on vgs invocation. Parent PID 23172: grub-install
File descriptor 70 (socket:[62725]) leaked on vgs invocation. Parent PID 23172: grub-install
File descriptor 75 (socket:[62766]) leaked on vgs invocation. Parent PID 23172: grub-install
  WARNING: Failed to connect to lvmetad. Falling back to device scanning.
  Volume group "loop2p1" not found
  Cannot process volume group loop2p1
grub-install: error: disk `lvm/loop2p1' not found.
```

This is fixable by mounting $MAPPER in a loopback device https://superuser.com/questions/130955/how-to-install-grub-into-an-img-file , but the resulting image is not bootable, as grub can't find the root partition. I may need to provide a correct device.map, but I can't find one that works.

Also chrooting doesn't work, but that's probably to be expected.

**Comment by z3ntu** [comment]
For me, the `create-image.sh` script works fine.
And actually the whole bootstrap->compile->create-image process works fine with this branch: https://github.com/z3ntu/cross-hurd/tree/tmpnew (some parts borrowed from your PR #2)

Unfortunately it doesn't seem to want to boot, Mach starts fine, the first parts of hurd apparently as well, but then `Starting the HURD...` appears and not much more. I'll investigate some more

`fsysopts / --update --writable` seems to hang...

**Comment by Gooberpatrol66** [comment]
No, I still get the same error with your branch.

**Comment by z3ntu** [comment]
Weird, what's your host system? Also does any device show up with `losetup -l`? It's weird that it tries anything with lvm because the script just uses losetup to set up the loop device and then kpartx to expose the subpartitions of the loop device.

**Comment by Gooberpatrol66** [comment]
```
nathan@gentoolaptop ~ $ losetup -l
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                                DIO LOG-SEC
/dev/loop1         0      0         1  0 /var/lib/systemd-swap/swapfc/1 (deleted)   1     512
/dev/loop0         0      0         0  1 /var/lib/anbox/android_amd64.img           0     512
nathan@gentoolaptop ~ $ uname -r
5.2.0-gentoo
```
I have seet $LOOP to /dev/loop2 and $MAPPER to /dev/mapper/loop2p1 because the others are in use.
According to that superuser link, this error is to be expected, so I don't know how you're avoiding it.

**Comment by z3ntu** [comment]
Found this quote in the [Gentoo Forums](https://forums.gentoo.org/viewtopic-t-1050746-start-0.html):

> Be sure that you have grub compiled with devicemapper support. Anything in /dev/mapper is either related to devicemapper or LVM. If you disable devicemapper support in grub then the resulting grub will assume everything in /dev/mapper/ is LVM.

That sounds pretty similar to what you are seeing.

**Comment by Gooberpatrol66** [comment]
Ah, that was the problem. I'm able to boot it and login now.
